docker_compose(["../docker-compose.yml", "../docker-compose.data.yml", "../docker-compose.docker.yml"], project_name = "lana-bank")
docker_groups = {
    "auth": ["kratos-admin", "kratos-admin-pg", "kratos-customer", "kratos-customer-pg", "oathkeeper"],
    "otel": ["otel-agent"],
    "core": ["core-pg"],
    "airflow": ["airflow-scheduler", "airflow-webserver", "airflow-pg"],
    "email": ["mailcrab"]
}

for service, deps in docker_groups.items():
    for dep in deps:
        dc_resource(dep, labels = [service])

bfx_local_price = os.getenv("BFX_LOCAL_PRICE", "1")
serve_env_core = {
    "PG_CON": "postgres://user:password@localhost:5433/pg?sslmode=disable",
    "OTEL_EXPORTER_OTLP_ENDPOINT": "http://localhost:4317",
    "BFX_LOCAL_PRICE": bfx_local_price
}
local_resource(
    "core",
    labels = ["core"],
    serve_cmd = "cd .. && make setup-db run-server",
    serve_env = serve_env_core,
    readiness_probe = probe(
        initial_delay_secs = 10,
        period_secs = 1,
        http_get = http_get_action(
            path = "/graphql",
            port = 5253,
        ),
    ),
    allow_parallel = True,
    resource_deps = [
        "core-pg",
    ],
    links = [
        link("http://admin.localhost:4455/graphql", "playground"),
    ]
)

local_resource(
    "admin-panel",
    labels = ["apps"],
    serve_env = {
        "NEXT_PUBLIC_CORE_ADMIN_URL": "/graphql"
    },
    serve_cmd = "cd .. && make start-admin",
    readiness_probe = probe(
        initial_delay_secs = 10,
        period_secs = 1,
        http_get = http_get_action(
            path = "/",
            port = 3001,
        ),
    ),
    allow_parallel = True,
    links = [
        link("http://admin.localhost:4455", "admin-panel"),
    ]
)

local_resource(
    "customer-portal",
    labels = ["apps"],
    serve_env = {
        "NEXT_PUBLIC_CORE_APP_URL": "/graphql"
    },
    serve_cmd = "cd .. && make start-customer-portal",
    readiness_probe = probe(
        initial_delay_secs = 10,
        period_secs = 1,
        http_get = http_get_action(
            path = "/",
            port = 3002,
        ),
    ),
    allow_parallel = True,
    links = [
        link("http://app.localhost:4455", "customer-portal"),
    ]
)
